config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :products do 
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins

  authenticated :admin do
    root to: "admin#index", as: :admin_root
  end

  get "admin" =>  "admin#index"


  resources :categories, only: [:show]
  resources :products, only: [:show]

  root "home#index"

end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
end

app/controllers/admin/stocks_controller.rb
class Admin::StocksController < AdminController
  before_action :set_admin_stock, only: %i[ show edit update destroy ]

  # GET /admin/stocks or /admin/stocks.json
  def index
    @admin_stocks = Stock.where(product_id: params[:product_id])
  end

  # GET /admin/stocks/1 or /admin/stocks/1.json
  def show
  end

  # GET /admin/stocks/new
  def new
    @product = Product.find(params[:product_id])
    @admin_stock = Stock.new
  end

  # GET /admin/stocks/1/edit
  def edit
    @product = Product.find(params[:product_id])
    @admin_stock = Stock.find(params[:id])
  end

  # POST /admin/stocks or /admin/stocks.json
  def create
    @product = Product.find(params[:product_id])
    @admin_stock = @product.stocks.new(admin_stock_params)

    respond_to do |format|
      if @admin_stock.save
        format.html { redirect_to admin_product_stock_url(@product, @admin_stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @admin_stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/stocks/1 or /admin/stocks/1.json
  def update
    respond_to do |format|
      if @admin_stock.update(admin_stock_params)
        format.html { redirect_to admin_product_stock_url(@admin_stock.product, @admin_stock), notice: "Stock was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @admin_stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/stocks/1 or /admin/stocks/1.json
  def destroy
    @admin_stock.destroy!

    respond_to do |format|
      format.html { redirect_to admin_product_stocks_url, notice: "Stock was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_stock
      @admin_stock = Stock.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def admin_stock_params
      params.expect(stock: [:amount, :size])
    end
end

app/helpers/admin/stocks_helper.rb
module Admin::StocksHelper
end

app/views/admin/stocks/_form.html.erb
<%= form_with(model: [:admin, @product, admin_stock], class: "contents") do |form| %>
  <% if admin_stock.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(admin_stock.errors.count, "error") %> prohibited this admin_stock from being saved:</h2>

      <ul class="list-disc ml-6">
        <% admin_stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :amount %>
    <%= form.number_field :amount, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": admin_stock.errors[:amount].none?, "border-red-400 focus:outline-red-600": admin_stock.errors[:amount].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :size %>
    <%= form.text_field :size, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": admin_stock.errors[:size].none?, "border-red-400 focus:outline-red-600": admin_stock.errors[:size].any?}] %>
  </div>
 
  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/stocks/_stock.html.erb
<div id="<%= dom_id stock %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Product:</strong>
    <%= stock.product_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Amount:</strong>
    <%= stock.amount %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Size:</strong>
    <%= stock.size %>
  </div>
</div>

app/views/admin/stocks/edit.html.erb
<% content_for :title, "Editing stock" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing stock</h1>

  <%= render "form", admin_stock: @admin_stock %>

  <%= link_to "Show this stock", [:admin, @product, @admin_stock], class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to stocks", admin_product_stocks_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/admin/stocks/index.html.erb
<% content_for :title, "Stocks" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Stocks</h1>
    <%= link_to "New stock", new_admin_product_stock_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="admin_stocks" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @admin_stocks.any? %>
      <% @admin_stocks.each do |admin_stock| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render admin_stock %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", [:admin, admin_stock.product, admin_stock], class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_admin_product_stock_path(admin_stock.product, admin_stock), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", [:admin, admin_stock.product, admin_stock], method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No stocks found.</p>
    <% end %>
  </div>
</div>

app/views/admin/stocks/new.html.erb
<% content_for :title, "New stock" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New stock</h1>

  <%= render "form", admin_stock: @admin_stock %>

  <%= link_to "Back to stocks", admin_product_stocks_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/admin/stocks/show.html.erb
<% content_for :title, "Showing stock" %>
<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>
  <h1 class="font-bold text-4xl">Showing stock</h1>
  <%= render @admin_stock %>
  <%= link_to "Edit this stock", edit_admin_product_stock_path(@admin_stock.product, @admin_stock), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to stocks", admin_product_stocks_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this stock", admin_product_stock_path(@admin_stock.product, @admin_stock), method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>