config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :products do 
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins

  authenticated :admin do
    root to: "admin#index", as: :admin_root
  end

  get "admin" =>  "admin#index"


  resources :categories, only: [:show]
  resources :products, only: [:show]

  root "home#index"

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Food App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Food App">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <script src="https://unpkg.com/@tailwindcss/browser@4"></script>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class="flex">
      <nav class="flex w-56">
        <div class="w-64 p-4 h-screen bg-gray-600 sticky top-0">
          <div class="flex">
            <%= image_tag "logo.jpg", class: 'w-16' %>
            <h1 class="text-md py-2 text-gray-50 font-bold hidden md:block">FoodApp</h1>
          </div>
          <ul class="flex flex-col text-gray-50">
            <li>
              <%= link_to admin_path, class:"block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <%= icon('fa-solid', 'gauge-high') %>
                <span class="hidden md:inline-block">Dashboard</span>
              <% end %>
            </li>
            <li>
              <%= link_to admin_products_path, class:"block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <%= icon('fa-solid', 'cart-shopping') %>
                <span class="hidden md:inline-block">Product</span>
              <% end %>
            </li>
            <li>
              <%= link_to admin_categories_path, class:"block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <%= icon('fa-solid', 'list') %>
                <span class="hidden md:inline-block">Category</span>
              <% end %>
            </li>
            <li>
              <%= link_to admin_orders_path, class:"block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <%= icon('fa-solid', 'truck-fast') %>
                <span class="hidden md:inline-block">Orders</span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_admin_session_path, data:{"turbo-method": "delete", "turbo-confirm": "Deseja sair do sistema?"}, class:"block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <%= icon('fa-solid', 'sign-out') %>
                <span class="hidden md:inline-block">Logout</span>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
      <div class="w-full p-8">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Food App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Food App">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

		<script src="https://unpkg.com/@tailwindcss/browser@4"></script>
		
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    
    <%= javascript_importmap_tags %>
  </head>
  <body>
		<%= render "shared/navbar" %>
    <main class="container mx-auto mt-28 max-w-7x1 px-2 sm:px-6 lg:px-8">
      <%= yield %>
    </main>
		<%= render "shared/footer" %>
  </body>
</html>